### ISSUE TITLE
How to move files to phone storage

### ISSUE THREAD

**Issue by Onibenjo** [alpha0010/react-native-file-access#1]
Nice library, I noticed that Dirs only points to the apps storage on android and not the phone storage. Is there a way to move/copy files from the cache to the phone storage? or is this a bug?

**Comment by Onibenjo** [comment]
Ok, it is not a bug. Please any workaround around this?

**Comment by alpha0010** [comment]
Dirs constant does not currently have paths (though internal code technically has no restrictions against access).  Android is moving toward requiring `MediaStore` api for apps interacting with shared phone storage and I am uncertain how best to implement (without diverging too far from iOS if possible, ideally avoiding need for Platform.OS checks for apps using this library).

**Comment by alpha0010** [comment]
Fixed in v0.6.0.

**Comment by Onibenjo** [comment]
Oh OK thanks
