### ISSUE TITLE
Get base64 from external image

### ISSUE THREAD

**Issue by tux240** [alpha0010/react-native-file-access#12]
Is it possible to get the base64 data from an external image ?

Actually, I have this code : 
`await FileSystem.fetch(props.currentMessage.image, {path: Dirs.CacheDir + '/image.jpg'});`

is it possible to get the base64 data from the cache path ? (Dirs.CacheDir + '/image.jpg')

Thanks

**Comment by alpha0010** [comment]
Not yet implemented; will see what I can do soon.
