### ISSUE TITLE
Is there a way to unlink a directory?

### ISSUE THREAD

**Issue by ahmetbicer** [alpha0010/react-native-file-access#21]
`FileSystem.unlink` method seems to only work for files. Is there a way to delete whole directory?

Thanks!

**Comment by alpha0010** [comment]
Should already work on iOS.  For Android, I believe it only works if the directory is empty (OS default behavior).

Will try to add Android support for non-empty directories soon.

**Comment by ahmetbicer** [comment]
Thank you so much! By the way [this](https://github.com/itinance/react-native-fs/blob/baf88b3603df325d76e1b1c5633856cbdefd6692/android/src/main/java/com/rnfs/RNFSManager.java#L646) is the implementation in `react-native-fs`, looks like they recursively deleting the directory content, maybe it can be helpful.
