### ISSUE TITLE
written file does not show up and many files not shown with FileSystem.ls

### ISSUE THREAD

**Issue by FrederickEngelhardt** [alpha0010/react-native-file-access#24]
Written files that I write to download are not showing up.

File extensions missing are`[apk, txt,bak,pdf,docx]`

Are there file extensions that are ignored? Is there a permission I am missing?

Example
```
const downloadPath =`${Dirs.SDCardDir}/Download`
const output = await FileSystem.ls(`${Dirs.SDCardDir}/Download`)
```

**Comment by alpha0010** [comment]
Nothing should be ignored.  Do you have `READ_EXTERNAL_STORAGE` and/or `WRITE_EXTERNAL_STORAGE` granted https://reactnative.dev/docs/permissionsandroid ?  Are there any error messages?

**Comment by alpha0010** [comment]
Note that file access has become a lot more restrictive on recent API levels https://developer.android.com/training/data-storage; using `Dirs.SDCardDir` is likely to fail on API 29+.

I have not implemented all features of MediaStore and Storage Access Framework.  If your use case is not possible with this library (but is compatible with Android's new permissions model), let me know and I will see what I can do.

**Comment by FrederickEngelhardt** [comment]
I ended up resolving this issue by adding the following the the `android/app/src/main/AndroidManifest.xml`

```
    <application
      android:requestLegacyExternalStorage="true"
```
