### ISSUE TITLE
Question: How do we read external storage

### ISSUE THREAD

**Issue by FrederickEngelhardt** [alpha0010/react-native-file-access#29]
I'm not seeing a read external storage directory command. Does one exist?

Thanks!

Update:

Upon playing around with the paths it looks like `/storage/` is the root folder that contains the externalSD and internal sd.

**Comment by alpha0010** [comment]
`Dirs.SDCardDir` should also give you that folder (though constant may be null if code is not certain).  Be aware that targeting latest Android API will require broad permission `MANAGE_EXTERNAL_STORAGE` to read/write directly there.

Alternatively if you get a content uri (e.g. from `react-native-image-picker`), it should work as a path parameter to other API calls in this library (without requiring special permissions).

**Comment by alpha0010** [comment]
Assuming resolved.
