### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by zimzika** [alpha0010/react-native-file-access#31]
I'm learning react-native in practice and I'm just trying to get the directorof my phone, but you have this error: TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[0], "react-native-file-access").Dirs.DocumentDir')

**Comment by zimzika** [comment]
Sorry :) need permissions

**Comment by dondxniel** [comment]
@zimzika How did you get permissions? `Dirs` is returning undefined for me.
