### ISSUE TITLE
FileSystem.fetch Error: Expected URL scheme

### ISSUE THREAD

**Issue by CostachescuCristinel** [alpha0010/react-native-file-access#36]
When fetching to file on Android (did not try iOS yet), the call always fails with the error:
```
Error: Expected URL scheme 'http' or 'https' but no colon was found
```

This is the code that I am using:
```javascript
import { Dimensions } from "react-native";
import { Dirs, FileSystem } from "react-native-file-access";
import "react-native-get-random-values"; // make sure to import before "uuid";
import * as uuid from "uuid";

const SCREEN_WIDTH = Dimensions.get("screen").width;

function download(url, accessToken){
    // url = "https://my.website.com/uploaded/12345"

    const headers = { Cookie: `token=${accessToken}` };
    const method = "GET";
    const path = `${url}?max_width=${SCREEN_WIDTH}`;
    const localFilePath = `${Dirs.CacheDir}/${uuid.v4()}.cache`;
    
    return FileSystem.fetch(localFilePath, { headers, method, path }).then((result) => {
        if (result.ok === false){ return Promise.reject(result); }
        return Promise.resolve(localFilePath);
    });
}
```

Can you please let me know what is wrong in the call above?
I tried adding `scheme: "https"` to the init object, received the same error

**Environment**
`react-native-file-access@1.7.1 | MacOS BigSur (Intel) |  expo bare workflow (SDK43) | react-native 0.64.3 | nodejs@14.18.0 | Android Studio 2020.3.1`

**Comment by alpha0010** [comment]
First parameter of `fetch()` is the URL to get; [`path`](https://github.com/alpha0010/react-native-file-access/blob/master/src/index.ts#L105) in the config parameter is the destination to save the result.  So with this code, you would want something like:

```js
FileSystem.fetch(path, { headers, method, path: localFilePath }) // ...
```

**Comment by alpha0010** [comment]
Assuming resolved.
