### ISSUE TITLE
Saving to downloads directory

### ISSUE THREAD

**Issue by ShivamJoker** [alpha0010/react-native-file-access#37]
Hello thanks for your great work
Can we also save the files in download directory ?

**Comment by ShivamJoker** [comment]
I am trying using the external cp but getting
```
Error: Failed to copy to 'downloads'
```

**Comment by alpha0010** [comment]
Assuming Android, have you tried requesting `WRITE_EXTERNAL_STORAGE` https://reactnative.dev/docs/permissionsandroid ?

**Comment by ShivamJoker** [comment]
Okay even after adding permission that it is not working 

```sh
 LOG  file:///data/user/0/com.introverttest/cache/5fc1e891-2b3c-4dab-b85f-dc290b3d6cbdimagemarker.jpg
 LOG  [Error: Failed to copy to 'downloads' ('Introvert Certificate.jpg')]
```

```js
  const handleDownload = async () => {
    try {
      console.log(imgUri);

      await checkStoragePermission();
      const url = await FileSystem.cpExternal(
        imgUri,
        'downloads',
        'Introvert Certificate.jpg',
      );
      console.log('copied', url);
    } catch (err) {
      console.log(err);
    }
  };
```

**Comment by alpha0010** [comment]
Looks like arguments are reversed.  Try:
```js
await FileSystem.cpExternal(
  imgUri,
  'Introvert Certificate.jpg',
  'downloads',
);
```

(Related, if you decide to switch to using TypeScript at some point, this library includes definitions that should give a warning for this type of situation.)

**Comment by ShivamJoker** [comment]
Damn 🥺 yeah I generally use typescript in my projects but this was for someone else.

Thanks for replying
