### ISSUE TITLE
Replace deprecated rn-fetch-blob

### ISSUE THREAD

**Issue by RonRadtke** [alpha0010/react-native-file-access#40]
Hey,
just thought I'll inform you that I forked the rn-fetch-blob lib a while ago and am maintaining the fork still.
So would be great if you could change the link to https://github.com/RonRadtke/react-native-blob-util, so people don't have to dig in the issues there to find the fork :)

**Comment by alpha0010** [comment]
Thanks for the heads up; link updated.
