### ISSUE TITLE
Google Play: "Your app contains an unsafe unzipping pattern that may lead to a path traversal vulnerability"

### ISSUE THREAD

**Issue by afilp** [alpha0010/react-native-file-access#42]
I submitted the app to be released, it has been released.

However, Google Play Console shows this error in release dashboard:

![image](https://user-images.githubusercontent.com/7850073/152138415-8c404fe5-d2c5-4599-83f2-0919930d558b.png)

**Comment by alpha0010** [comment]
Thanks for the report.  You can revert to 2.1.0, which does not have zip support (assuming you do not need it) while I work on a fix.
