### ISSUE TITLE
readFile() freezes for some seconds when reading small files

### ISSUE THREAD

**Issue by andra961** [alpha0010/react-native-file-access#45]
Hi, is it normal that when i read a 2MB pdf through readFile() function with base64 encoding, the app freezes for some second?Perceived time would me much less if i could use a spinner while the file is being read, since readFile is async, but it doesn't work :(

**Comment by alpha0010** [comment]
Hmm, that does not seem right.  Is this Android, iOS, or both?  Simulator or physical device?

**Comment by andra961** [comment]
> Hmm, that does not seem right. Is this Android, iOS, or both? Simulator or physical device?

Android, tried on both emulator and physical device, same result. I also tried 'react-native-blob-util', the other package you suggest, and even though its readFile() also takes 1-2 seconds to load, atleast the spinner works with it since ui doesn't freeze(it has other problems though).

**Comment by alpha0010** [comment]
Should be fixed in v2.2.2.
