### ISSUE TITLE
Add installation guides

### ISSUE THREAD

**Issue by amerllica** [alpha0010/react-native-file-access#50]
**Feature**
Installation Guide

**Motivation**
Definitely, these kinds of libraries were written by brown-field of RN, so it would be better to add some guides like `pod install` and manual linking for projects with legacy versions.

**Details**
- Auto-linking
- iOS: manual linking
- Android: manual linking

**Comment by amerllica** [comment]
@alpha0010, I meant to add `pod install`, you haven't added this, it's so simple but definitely we should have it in README.md file

**Comment by alpha0010** [comment]
Whoops, yes.  That makes sense.  Somehow I missed that when reading your suggestion.
