### ISSUE TITLE
Support for new react native architecture

### ISSUE THREAD

**Issue by Miraj98** [alpha0010/react-native-file-access#53]
**Feature**
Support for the new react native architecture

**Motivation**
A lot of libraries use this library internally (e.g. react-native-image-cache). Making sure this library supports new architecture can be helpful for a lot of other library

**Comment by alpha0010** [comment]
In my radar, though I currently do not have the development bandwidth to work on this, so no time estimate.

**Comment by alpha0010** [comment]
Started implementation: [newarch](https://github.com/alpha0010/react-native-file-access/tree/newarch) branch
