### ISSUE TITLE
Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by jamninetyfive** [alpha0010/react-native-file-access#59]
react-native: 0.70.6
react-native-file-access: 2.5.0
Platform: iOS

**Bug**

**To reproduce**
Describe how to trigger this bug.

**Details**
Logs, code snippets, screenshots, extended bug description.

when i writeFile with base64 to png, i got this error.

![image](https://user-images.githubusercontent.com/5283666/203927603-f1e102e7-7b31-4790-a588-94166d3a2ace.png)

**Comment by jamninetyfive** [comment]
need help. 

data was base64 why got nil .

path :/var/mobile/Containers/Data/Application/EC6573D6-86F2-4A5C-AD1D-79F20CFE9316/Library/Caches/XXX.png

**Comment by alpha0010** [comment]
The error is due to the prefix `data:image/png;base64,` is not valid base64.  You should pass only the data part `iVBORw...`.

That said, this is supposed create an error message, not crash the app.

**Comment by jamninetyfive** [comment]
same. The first thing I tried was not data: image/png; base64. got crash.

Base64 data from [react-native-qrcode-svg ](https://github.com/awesomejerry/react-native-qrcode-svg) toDataURL

when i add data: image/png; base64 to iVBORw it work in there. https://products.aspose.app/imaging/zh-hans/conversion/base64-to-png

**Comment by jamninetyfive** [comment]
fixed #60
