### ISSUE TITLE
Feature Request: Write File from Buffer

### ISSUE THREAD

**Issue by lucsoft** [alpha0010/react-native-file-access#6]

**Comment by alpha0010** [comment]
Could you describe how this is different than the existing `FileSystem.writeFile(path: string, data: string)`?

**Comment by lucsoft** [comment]
Because data only can be string as the types says

**Comment by alpha0010** [comment]
(Assuming referring to https://nodejs.org/api/buffer.html), does accepting base 64 encoded strings meet your goal?  `Buffer` is not included in the base React Native (of course, users can add it as a dependency), so potentially a user would have a different source of binary data.

So for example if using `Buffer`, the api call could be something like `FileSystem.writeFile(path, buf.toString('base64'), 'base64')`?

**Comment by alpha0010** [comment]
Done in 72da4f85243b35b332c026d7360bf704c8574841.
