### ISSUE TITLE
Android - getting error while generating apk

### ISSUE THREAD

**Issue by KiranRadish** [alpha0010/react-native-file-access#64]
react-native: "0.71.2"
react-native-file-access: 2.5.3
Platform:  `Android`

**Bug**
**A clear and concise description of what the bug is.**
While generating release apk i am getting errors 

**To reproduce**
**Describe how to trigger this bug.**
generate release apk

**Details**
Logs, code snippets, screenshots, extended bug description.
`node_modules/react-native-file-access/android/build/.transforms/ba5c59326539780ce213966ce792062f/transformed/out/jars/classes.jar!/META-INF/react-native-file-access_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`
`.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.10/6d5560a229477df9406943d5feda5618e98eb64c/kotlin-stdlib-1.8.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.`

**Comment by alpha0010** [comment]
Assuming resolved.
